name: GitHub Action
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Built:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Clone minilibx-linux
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        uses: actions/checkout@v3
        with:
          repository: josean-dev/dev-environment-files
          path: ./minilibx-linux
      - name: Make re
        run: ls ${{github.workspace}}
        run: make re
