name: Build check
run-name: ${{ github.actor }} is testing out Build Check 🚀
on: [push]
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: env set
        run: "sudo apt-get update && sudo apt-get install xorg libxext-dev zlib1g-dev libbsd-dev"
      - name: Clone minilibx-linux
        uses: actions/checkout@v3
        with:
          repository: 42Paris/minilibx-linux
          path: ./minilibx-linux
      - name: Make re
        run: make re
      - name: ls
        run: "ls ${{github.workspace}}"
