name: UnitTest
run-name: ${{ github.actor }} is testing out Unit Test 🚀
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Clone minilibx-linux
        uses: actions/checkout@v3
        with:
          repository: 42Paris/minilibx-linux
          path: ./minilibx-linux
      - name: make minilibx
        run: make -C ./minilibx-linux/
      - uses: actions/checkout@v3
      - name: env
        run: "sudo apt update && sudo apt install -y libcunit1-dev"
      - name: complile
        run: make UnitTest

