name: UnitTest
run-name: ${{ github.actor }} is testing out Unit Test 🚀
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: env
        run: "sudo apt update && sudo apt install -y libcunit1-dev"
      - name: complile
        run: make UnitTest

